### ISSUE TITLE
добавление НДС 20%

### ISSUE THREAD

**Issue by mavDev** [Platron/atol-sdk-api-v4#2]
Добрый день, не могли бы вы добавить поддержку нового НДС?

**Comment by lashnag** [comment]
Добрый день! К сожалению, АТОЛ пока не поддерживает новый НДС
https://online.atol.ru/files/API_FFD_1-0-5.pdf

**Comment by basicdecor** [comment]
Добрый день. 
В документации по api v4 (версия доки 4.6) есть описание vat20. Эту версию атол отправляет по запросу в поддержку.

**Comment by lashnag** [comment]
Добрый день. Atol сообщил, что до 1 февраля будет поддерживаться НДС 18%, на их стороне будет происходить конвертация. До 1 февраля будет изменено SDK. Изменение раньше чревато отправкой НДС 20% ранее 1 января, что приведет к ошибке

**Comment by mavDev** [comment]
Да, есть такое дело. Вы наверно имели в виду, что Вы сделаете изменения после первого января? В общем разумно.
